site_name: FreeLing 4.0 User Manual
copyright: TALP Research Center - Universitat Politècnica de Catalunya
nav:
    - Home: index.md
    - Index: toc.md

markdown_extensions:
    - toc:
        permalink: 
        baselevel: 2
         