site_name: FreeLing User Manual
copyright: TALP Research Center - Universitat Politècnica de Catalunya
nav:
    - Home: index.md
    - Index: toc.md

markdown_extensions:
    - toc:
        permalink: 
        baselevel: 2